// Copyright 2026 printing-press-golden. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	_ "modernc.org/sqlite"
)

const schemaVersion = 1

var unsafeIdent = regexp.MustCompile(`[^A-Za-z0-9_]`)

// Store wraps the local SQLite database used by sync, doctor, and MCP tools.
type Store struct {
	db *sql.DB
}

// OpenWithContext opens or creates a writable local store and applies migrations.
func OpenWithContext(ctx context.Context, dbPath string) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(dbPath), 0o700); err != nil {
		return nil, fmt.Errorf("creating database directory: %w", err)
	}
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		return nil, err
	}
	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		return nil, err
	}
	s := &Store{db: db}
	if err := s.migrate(ctx); err != nil {
		_ = db.Close()
		return nil, err
	}
	return s, nil
}

// OpenReadOnly opens an existing store in SQLite read-only mode.
func OpenReadOnly(dbPath string) (*Store, error) {
	u := url.URL{Scheme: "file", Path: dbPath, RawQuery: "mode=ro"}
	db, err := sql.Open("sqlite", u.String())
	if err != nil {
		return nil, err
	}
	if err := db.Ping(); err != nil {
		_ = db.Close()
		return nil, err
	}
	return &Store{db: db}, nil
}

func (s *Store) migrate(ctx context.Context) error {
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS schema_meta (version INTEGER NOT NULL)`,
		`INSERT INTO schema_meta(version) SELECT ? WHERE NOT EXISTS (SELECT 1 FROM schema_meta)`,
		`CREATE TABLE IF NOT EXISTS sync_state (
			resource_type TEXT PRIMARY KEY,
			next_cursor TEXT NOT NULL DEFAULT '',
			total_count INTEGER NOT NULL DEFAULT 0,
			last_synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE TABLE IF NOT EXISTS records (
			resource_type TEXT NOT NULL,
			id TEXT NOT NULL,
			data TEXT NOT NULL,
			parent_id TEXT,
			updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY(resource_type, id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_records_resource ON records(resource_type)`,
	}
	for i, stmt := range stmts {
		if i == 1 {
			if _, err := s.db.ExecContext(ctx, stmt, schemaVersion); err != nil {
				return err
			}
			continue
		}
		if _, err := s.db.ExecContext(ctx, stmt); err != nil {
			return err
		}
	}
	_, err := s.db.ExecContext(ctx, `UPDATE schema_meta SET version = ?`, schemaVersion)
	return err
}

func (s *Store) Close() error {
	if s == nil || s.db == nil {
		return nil
	}
	return s.db.Close()
}

func (s *Store) DB() *sql.DB {
	return s.db
}

func (s *Store) Query(query string, args ...any) (*sql.Rows, error) {
	return s.db.Query(query, args...)
}

func (s *Store) SchemaVersion() (int, error) {
	var version int
	err := s.db.QueryRow(`SELECT version FROM schema_meta LIMIT 1`).Scan(&version)
	return version, err
}

func (s *Store) GetSyncState(resource string) (string, time.Time, int, error) {
	var cursor string
	var lastSynced time.Time
	var total int
	err := s.db.QueryRow(
		`SELECT next_cursor, last_synced_at, total_count FROM sync_state WHERE resource_type = ?`,
		resource,
	).Scan(&cursor, &lastSynced, &total)
	if err == sql.ErrNoRows {
		return "", time.Time{}, 0, nil
	}
	return cursor, lastSynced, total, err
}

func (s *Store) SaveSyncState(resource, nextCursor string, totalCount int) error {
	_, err := s.db.Exec(
		`INSERT INTO sync_state(resource_type, next_cursor, total_count, last_synced_at)
		 VALUES (?, ?, ?, CURRENT_TIMESTAMP)
		 ON CONFLICT(resource_type) DO UPDATE SET
		   next_cursor = excluded.next_cursor,
		   total_count = excluded.total_count,
		   last_synced_at = excluded.last_synced_at`,
		resource,
		nextCursor,
		totalCount,
	)
	return err
}

func (s *Store) UpsertBatch(resource string, items []json.RawMessage) (int, int, error) {
	stored := 0
	extractFailures := 0
	for _, item := range items {
		var obj map[string]any
		if err := json.Unmarshal(item, &obj); err != nil {
			extractFailures++
			continue
		}
		id := extractID(obj)
		if id == "" {
			extractFailures++
			continue
		}
		if err := s.Upsert(resource, id, item); err != nil {
			return stored, extractFailures, err
		}
		stored++
	}
	return stored, extractFailures, nil
}

func (s *Store) UpsertProjects(data json.RawMessage) error {
	return s.upsertObject("projects", data)
}

func (s *Store) UpsertTasks(data json.RawMessage) error {
	return s.upsertObject("tasks", data)
}

func (s *Store) UpsertSummary(data json.RawMessage) error {
	return s.Upsert("summary", "summary", data)
}

func (s *Store) upsertObject(resource string, data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return err
	}
	id := extractID(obj)
	if id == "" {
		id = resource
	}
	return s.Upsert(resource, id, data)
}

func (s *Store) Upsert(resource, id string, data json.RawMessage) error {
	resource = strings.TrimSpace(resource)
	id = strings.TrimSpace(id)
	if resource == "" {
		return fmt.Errorf("resource is required")
	}
	if id == "" {
		return fmt.Errorf("id is required")
	}
	parentID := parentIDFromRaw(data)
	if err := s.ensureResourceTable(resource); err != nil {
		return err
	}
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			_ = tx.Rollback()
		}
	}()
	if _, err = tx.Exec(
		`INSERT INTO records(resource_type, id, data, parent_id, updated_at)
		 VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
		 ON CONFLICT(resource_type, id) DO UPDATE SET
		   data = excluded.data,
		   parent_id = excluded.parent_id,
		   updated_at = excluded.updated_at`,
		resource,
		id,
		string(data),
		parentID,
	); err != nil {
		return err
	}
	table := quoteIdent(tableName(resource))
	if _, err = tx.Exec(
		fmt.Sprintf(`INSERT INTO %s(id, data, parent_id, updated_at)
		 VALUES (?, ?, ?, CURRENT_TIMESTAMP)
		 ON CONFLICT(id) DO UPDATE SET
		   data = excluded.data,
		   parent_id = excluded.parent_id,
		   updated_at = excluded.updated_at`, table),
		id,
		string(data),
		parentID,
	); err != nil {
		return err
	}
	err = tx.Commit()
	return err
}

func (s *Store) ensureResourceTable(resource string) error {
	table := quoteIdent(tableName(resource))
	_, err := s.db.Exec(fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s (
		id TEXT PRIMARY KEY,
		data TEXT NOT NULL,
		parent_id TEXT,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`, table))
	return err
}

func (s *Store) Search(query string, limit int) ([]map[string]any, error) {
	if limit <= 0 {
		limit = 25
	}
	like := "%" + strings.ReplaceAll(query, "%", `\%`) + "%"
	rows, err := s.db.Query(
		`SELECT resource_type, id, data, updated_at
		 FROM records
		 WHERE data LIKE ? ESCAPE '\'
		 ORDER BY updated_at DESC
		 LIMIT ?`,
		like,
		limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []map[string]any
	for rows.Next() {
		var resource, id, raw, updated string
		if err := rows.Scan(&resource, &id, &raw, &updated); err != nil {
			return nil, err
		}
		row := map[string]any{
			"resource":   resource,
			"id":         id,
			"updated_at": updated,
		}
		var decoded any
		if err := json.Unmarshal([]byte(raw), &decoded); err == nil {
			row["data"] = decoded
		} else {
			row["data"] = raw
		}
		results = append(results, row)
	}
	return results, rows.Err()
}

func (s *Store) List(resource string, limit int) ([]json.RawMessage, error) {
	query := `SELECT data FROM records WHERE resource_type = ? ORDER BY updated_at DESC`
	args := []any{resource}
	if limit > 0 {
		query += ` LIMIT ?`
		args = append(args, limit)
	}
	rows, err := s.db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []json.RawMessage
	for rows.Next() {
		var raw string
		if err := rows.Scan(&raw); err != nil {
			return nil, err
		}
		out = append(out, json.RawMessage(raw))
	}
	return out, rows.Err()
}

func (s *Store) ListIDs(resource string) ([]string, error) {
	rows, err := s.db.Query(`SELECT id FROM records WHERE resource_type = ? ORDER BY id`, resource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

func LookupFieldValue(obj map[string]any, field string) any {
	if obj == nil || field == "" {
		return nil
	}
	current := any(obj)
	for _, part := range strings.Split(field, ".") {
		m, ok := current.(map[string]any)
		if !ok {
			return nil
		}
		current = lookupSingle(m, part)
		if current == nil {
			return nil
		}
	}
	return current
}

func lookupSingle(obj map[string]any, field string) any {
	candidates := []string{field, toSnake(field), toCamel(field)}
	for _, candidate := range candidates {
		if v, ok := obj[candidate]; ok {
			return v
		}
	}
	for k, v := range obj {
		if strings.EqualFold(k, field) || strings.EqualFold(k, toSnake(field)) || strings.EqualFold(k, toCamel(field)) {
			return v
		}
	}
	return nil
}

func extractID(obj map[string]any) string {
	for _, key := range []string{"id", "uuid", "key", "slug", "name"} {
		if v := LookupFieldValue(obj, key); v != nil {
			s := fmt.Sprintf("%v", v)
			if s != "" && s != "<nil>" {
				return s
			}
		}
	}
	return ""
}

func parentIDFromRaw(data json.RawMessage) any {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil
	}
	return LookupFieldValue(obj, "parent_id")
}

func tableName(resource string) string {
	name := unsafeIdent.ReplaceAllString(resource, "_")
	name = strings.Trim(name, "_")
	if name == "" {
		return "resource"
	}
	if name[0] >= '0' && name[0] <= '9' {
		name = "r_" + name
	}
	return name
}

func quoteIdent(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}

func toSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r + ('a' - 'A'))
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

func toCamel(s string) string {
	parts := strings.Split(s, "_")
	if len(parts) == 1 {
		return s
	}
	var b strings.Builder
	b.WriteString(parts[0])
	for _, part := range parts[1:] {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}
