"""Characterization: the legacy ``manus`` binary alias must keep working.

Per the CRITICAL refactor-only invariant (Reviewer 2 / Coordinator): the router
ships a legacy ``manus`` command alias alongside the primary ``skill-router``
binary. Consolidating the *manus-skills-marketplace repo* (Goal 2) must NOT
remove the *manus command alias*. Breaking it is a CHANGES_REQUESTED blocker.

This pins two things:

* **Binary behaviour** — the same binary invoked as ``manus`` resolves a known
  skill and validates the manifest identically (run against the frozen fixture).
* **Declared contract** — the live ``manifest.json`` still advertises the
  ``manus`` legacy access path; ``docs/build_manifest.json`` (owned/generated by
  Builder 4) still records ``legacy_binary_alias == "manus"`` when present.
"""

from __future__ import annotations

import json
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import harness  # noqa: E402


class ManusBinaryAlias(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        try:
            harness.router_binary()
        except harness.RouterUnavailable as exc:
            raise unittest.SkipTest(str(exc))

    def test_manus_alias_resolves_known_skill(self):
        proc = harness.run_router_as_alias("manus", ["skill", "chat-summarizer"], fixture=True)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("chat-summarizer", proc.stdout)

    def test_manus_alias_validates_manifest_identically(self):
        proc = harness.run_router_as_alias(
            "manus", ["skills", "validate-manifest", "--json"], fixture=True,
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        data = json.loads(proc.stdout)
        self.assertTrue(data.get("ok"))
        self.assertEqual(data.get("totalSkills"), harness.fixture_skill_count())


class ManusDeclaredContract(unittest.TestCase):
    def test_manifest_declares_manus_legacy_access(self):
        manifest = harness.load_manifest()
        routing = manifest.get("routing")
        self.assertIsInstance(routing, dict, "manifest.json lost its routing block")
        legacy = (routing.get("legacy_access") or "")
        self.assertIn(
            "manus", legacy,
            f"manifest.routing.legacy_access must still advertise manus, got {legacy!r}",
        )

    def test_build_manifest_preserves_legacy_binary_alias(self):
        # docs/build_manifest.json is generated/owned by Builder 4; assert only if present.
        path = os.path.join(harness.repo_root(), "docs", "build_manifest.json")
        if not os.path.exists(path):
            self.skipTest("docs/build_manifest.json not present")
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        self.assertEqual(
            data.get("legacy_binary_alias"), "manus",
            "build_manifest must keep legacy_binary_alias == 'manus'",
        )


if __name__ == "__main__":
    unittest.main()
