// Copyright 2026 printing-press-golden. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/url"
	"os"
	"strings"

	"printing-press-golden-pp-cli/internal/client"
	"printing-press-golden-pp-cli/internal/store"
)

func isNetworkError(err error) bool {
	if err == nil {
		return false
	}
	var urlErr *url.Error
	if As(err, &urlErr) {
		err = urlErr.Err
	}
	var netErr *net.OpError
	if As(err, &netErr) {
		return true
	}
	var dnsErr *net.DNSError
	if As(err, &dnsErr) {
		return true
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "connection refused") ||
		strings.Contains(msg, "no such host") ||
		strings.Contains(msg, "network is unreachable") ||
		strings.Contains(msg, "i/o timeout") ||
		strings.Contains(msg, "timeout")
}

func resolveRead(ctx context.Context, c *client.Client, flags *rootFlags, resourceType string, isList bool, path string, params map[string]string, headers map[string]string) (json.RawMessage, DataProvenance, error) {
	switch flags.dataSource {
	case "local":
		if err := ensureLocalReadAllowed(resourceType, isList, path, params); err != nil {
			return nil, DataProvenance{}, err
		}
		return resolveLocal(ctx, resourceType, isList, params, "user_requested")
	case "live":
		data, err := c.GetWithHeaders(path, params, headers)
		return data, DataProvenance{Source: "live"}, err
	default:
		data, err := c.GetWithHeaders(path, params, headers)
		if err == nil {
			writeThroughCache(ctx, resourceType, data)
			return data, DataProvenance{Source: "live"}, nil
		}
		if !isNetworkError(err) {
			return nil, DataProvenance{}, err
		}
		if scopeErr := ensureLocalReadAllowed(resourceType, isList, path, params); scopeErr != nil {
			return nil, DataProvenance{}, fmt.Errorf("API unreachable and local fallback is unsafe for this scoped request: %w; original error: %v", scopeErr, err)
		}
		data, prov, fallbackErr := resolveLocal(ctx, resourceType, isList, params, "api_unreachable")
		if fallbackErr != nil {
			return nil, DataProvenance{}, fmt.Errorf("API unreachable and no local data. Run 'printing-press-golden-pp-cli sync' to enable offline access: %w", err)
		}
		return data, prov, nil
	}
}

func resolvePaginatedRead(ctx context.Context, c *client.Client, flags *rootFlags, resourceType string, path string, params map[string]string, headers map[string]string, fetchAll bool, cursorParam, nextCursorPath, hasMoreField string) (json.RawMessage, DataProvenance, error) {
	_ = fetchAll
	_ = cursorParam
	_ = nextCursorPath
	_ = hasMoreField
	return resolveRead(ctx, c, flags, resourceType, true, path, params, headers)
}

func ensureLocalReadAllowed(resourceType string, isList bool, path string, params map[string]string) error {
	if len(params) > 0 {
		return fmt.Errorf("local data-source cannot satisfy filtered %s request without over-broad cached results", resourceType)
	}
	if !isList {
		return fmt.Errorf("local data-source cannot satisfy scoped %s item request without an exact cached lookup", resourceType)
	}
	if !isBroadCollectionPath(resourceType, path) {
		return fmt.Errorf("local data-source cannot satisfy scoped path %q for %s without over-broad cached results", path, resourceType)
	}
	return nil
}

func isBroadCollectionPath(resourceType, pathValue string) bool {
	return strings.TrimSuffix(pathValue, "/") == "/"+resourceType
}

func resolveLocal(ctx context.Context, resourceType string, isList bool, _ map[string]string, reason string) (json.RawMessage, DataProvenance, error) {
	db, err := openStoreForRead(ctx, "printing-press-golden-pp-cli")
	if err != nil {
		return nil, DataProvenance{}, err
	}
	if db == nil {
		return nil, DataProvenance{}, fmt.Errorf("no local data. Run 'printing-press-golden-pp-cli sync' first")
	}
	defer db.Close()
	prov := localProvenance(db, resourceType, reason)
	if isList {
		items, err := db.List(resourceType, 0)
		if err != nil {
			return nil, DataProvenance{}, err
		}
		data, err := json.Marshal(items)
		return data, prov, err
	}
	items, err := db.List(resourceType, 1)
	if err != nil {
		return nil, DataProvenance{}, err
	}
	if len(items) == 0 {
		return nil, DataProvenance{}, fmt.Errorf("no local %s data", resourceType)
	}
	return items[0], prov, nil
}

func openStoreForRead(ctx context.Context, cliName string) (*store.Store, error) {
	dbPath := defaultDBPath(cliName)
	if _, err := os.Stat(dbPath); os.IsNotExist(err) {
		return nil, nil
	}
	return store.OpenWithContext(ctx, dbPath)
}

func localProvenance(db *store.Store, resourceType, reason string) DataProvenance {
	prov := DataProvenance{Source: "local", Reason: reason, ResourceType: resourceType}
	_, lastSynced, _, err := db.GetSyncState(resourceType)
	if err == nil && !lastSynced.IsZero() {
		prov.SyncedAt = &lastSynced
	}
	return prov
}

func writeThroughCache(ctx context.Context, resourceType string, data json.RawMessage) {
	db, err := store.OpenWithContext(ctx, defaultDBPath("printing-press-golden-pp-cli"))
	if err != nil {
		return
	}
	defer db.Close()
	var items []json.RawMessage
	if json.Unmarshal(data, &items) == nil && len(items) > 0 {
		_, _, _ = db.UpsertBatch(resourceType, items)
		return
	}
	_ = db.Upsert(resourceType, resourceType, data)
}
