// Copyright 2026 printing-press-golden. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type DeliverSink struct {
	Scheme string
	Target string
}

func ParseDeliverSink(spec string) (DeliverSink, error) {
	if spec == "" || spec == "stdout" {
		return DeliverSink{Scheme: "stdout"}, nil
	}
	idx := strings.Index(spec, ":")
	if idx == -1 {
		return DeliverSink{}, fmt.Errorf("unknown --deliver sink %q: expected scheme:target (supported: stdout, file:<path>, webhook:<url>)", spec)
	}
	scheme := spec[:idx]
	target := spec[idx+1:]
	switch scheme {
	case "file":
		if target == "" {
			return DeliverSink{}, fmt.Errorf("--deliver file:<path> requires a path")
		}
	case "webhook":
		if !strings.HasPrefix(target, "http://") && !strings.HasPrefix(target, "https://") {
			return DeliverSink{}, fmt.Errorf("--deliver webhook:<url> requires an http:// or https:// URL, got %q", target)
		}
	default:
		return DeliverSink{}, fmt.Errorf("unknown --deliver scheme %q (supported: stdout, file, webhook)", scheme)
	}
	return DeliverSink{Scheme: scheme, Target: target}, nil
}

func Deliver(sink DeliverSink, body []byte, compact bool) error {
	switch sink.Scheme {
	case "", "stdout":
		return nil
	case "file":
		if err := os.MkdirAll(filepath.Dir(sink.Target), 0o755); err != nil && filepath.Dir(sink.Target) != "." {
			return fmt.Errorf("creating deliver dir: %w", err)
		}
		tmp := sink.Target + ".tmp"
		if err := os.WriteFile(tmp, body, 0o600); err != nil {
			return fmt.Errorf("writing deliver tmp: %w", err)
		}
		return os.Rename(tmp, sink.Target)
	case "webhook":
		contentType := "application/json"
		if compact {
			contentType = "application/x-ndjson"
		}
		req, err := http.NewRequest(http.MethodPost, sink.Target, bytes.NewReader(body))
		if err != nil {
			return fmt.Errorf("building webhook request: %w", err)
		}
		req.Header.Set("Content-Type", contentType)
		req.Header.Set("User-Agent", "printing-press-golden-pp-cli/deliver")
		resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
		if err != nil {
			return fmt.Errorf("posting to webhook: %w", err)
		}
		defer resp.Body.Close()
		if resp.StatusCode >= 400 {
			return fmt.Errorf("webhook returned %s", resp.Status)
		}
		return nil
	default:
		return fmt.Errorf("unsupported deliver sink %q", sink.Scheme)
	}
}
