// Copyright 2026 printing-press-golden. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func newProjectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{Use: "projects", Short: "Manage projects"}
	cmd.AddCommand(newProjectsCreateCmd(flags))
	cmd.AddCommand(newProjectsListCmd(flags))
	tasks := &cobra.Command{Use: "tasks", Short: "Manage project tasks"}
	tasks.AddCommand(newProjectsTasksListProjectCmd(flags))
	tasks.AddCommand(newProjectsTasksUpdateProjectCmd(flags))
	cmd.AddCommand(tasks)
	return cmd
}

func newReportsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{Use: "reports", Short: "Reports commands"}
	cmd.AddCommand(&cobra.Command{
		Use:   "summary <year>",
		Short: "Get a report summary for a year",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			path := replacePathParam("/reports/{year}/summary", "year", args[0])
			data, prov, err := resolveRead(cmd.Context(), c, flags, "summary", false, path, nil, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				wrapped, err := wrapWithProvenance(data, prov)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	})
	return cmd
}

func newCurrenciesPromotedCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:         "currencies",
		Short:       "List supported currencies",
		Annotations: map[string]string{"pp:endpoint": "currencies.list", "pp:method": "GET", "pp:path": "/currencies", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "currencies", "/currencies", nil, nil, false, "cursor", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				wrapped, err := wrapWithProvenance(data, prov)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
}

func newSearchCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "search <query>",
		Short: "Search synced local data",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			db, err := openStoreForRead(cmd.Context(), "printing-press-golden-pp-cli")
			if err != nil {
				return err
			}
			if db == nil {
				return fmt.Errorf("no local data. Run 'printing-press-golden-pp-cli sync' first")
			}
			defer db.Close()
			results, err := db.Search(args[0], limit)
			if err != nil {
				return err
			}
			enc := json.NewEncoder(cmd.OutOrStdout())
			enc.SetIndent("", "  ")
			return enc.Encode(results)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 25, "Maximum results")
	return cmd
}

func newExportCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "export <resource>",
		Short: "Export live API data",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, err := c.Get("/"+args[0], nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			return printOutput(cmd.OutOrStdout(), data, true)
		},
	}
}

func newAgentContextCmd(rootCmd *cobra.Command) *cobra.Command {
	var pretty bool
	cmd := &cobra.Command{
		Use:         "agent-context",
		Short:       "Emit structured JSON describing this CLI for agents",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := map[string]any{
				"schema_version": "3",
				"cli": map[string]any{
					"name":        rootCmd.Name(),
					"description": rootCmd.Short,
					"version":     rootCmd.Version,
				},
				"auth": map[string]any{
					"mode": "api_key",
					"env_vars": []map[string]any{{
						"name":      "PRINTING_PRESS_GOLDEN_API_KEY",
						"kind":      "per_call",
						"required":  true,
						"sensitive": true,
					}},
				},
				"commands": collectAgentCommands(rootCmd),
			}
			enc := json.NewEncoder(os.Stdout)
			if pretty {
				enc.SetIndent("", "  ")
			}
			return enc.Encode(ctx)
		},
	}
	cmd.Flags().BoolVar(&pretty, "pretty", false, "indent JSON output")
	return cmd
}

type agentContextCommand struct {
	Name        string                `json:"name"`
	Use         string                `json:"use,omitempty"`
	Short       string                `json:"short,omitempty"`
	Annotations map[string]string     `json:"annotations,omitempty"`
	Flags       []agentContextFlag    `json:"flags,omitempty"`
	Subcommands []agentContextCommand `json:"subcommands,omitempty"`
}

type agentContextFlag struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Usage   string `json:"usage,omitempty"`
	Default string `json:"default,omitempty"`
}

func collectAgentCommands(c *cobra.Command) []agentContextCommand {
	children := c.Commands()
	sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
	out := make([]agentContextCommand, 0, len(children))
	for _, sub := range children {
		if sub.Hidden || sub.Name() == "agent-context" {
			continue
		}
		entry := agentContextCommand{Name: sub.Name(), Use: sub.Use, Short: sub.Short}
		if len(sub.Annotations) > 0 {
			entry.Annotations = sub.Annotations
		}
		sub.Flags().VisitAll(func(f *pflag.Flag) {
			entry.Flags = append(entry.Flags, agentContextFlag{Name: f.Name, Type: f.Value.Type(), Usage: f.Usage, Default: f.DefValue})
		})
		entry.Subcommands = collectAgentCommands(sub)
		out = append(out, entry)
	}
	return out
}

func newAnalyticsCmd(flags *rootFlags) *cobra.Command {
	return unsupportedGeneratedCmd("analytics")
}

func newWorkflowCmd(flags *rootFlags) *cobra.Command {
	return unsupportedGeneratedCmd("workflow")
}

func newStaleCmd(flags *rootFlags) *cobra.Command {
	return unsupportedGeneratedCmd("stale")
}

func newOrphansCmd(flags *rootFlags) *cobra.Command {
	return unsupportedGeneratedCmd("orphans")
}

func newLoadCmd(flags *rootFlags) *cobra.Command {
	return unsupportedGeneratedCmd("load")
}

func unsupportedGeneratedCmd(use string) *cobra.Command {
	return &cobra.Command{
		Use:   use,
		Short: use + " command is not generated for this fixture",
		RunE: func(cmd *cobra.Command, args []string) error {
			return fmt.Errorf("%s command is not generated for this fixture", use)
		},
	}
}
