param(
  [switch]$RestartPaperclip
)

$ErrorActionPreference = 'Stop'
$Root = Join-Path $env:USERPROFILE '.universal-ai-stack'
$SecretsEnv = Join-Path $Root 'secrets\.env'
$HermesEnv = Join-Path $env:USERPROFILE '.hermes\.env'
$PaperclipConfig = Join-Path $env:USERPROFILE '.paperclip\instances\default\config.json'
$KimiConfig = Join-Path $env:USERPROFILE '.kimi\config.toml'
$StateDir = Join-Path $Root 'state'

function Read-EnvFile {
  param([string]$Path)
  $values = [ordered]@{}
  if (!(Test-Path -LiteralPath $Path)) { return $values }
  foreach ($raw in Get-Content -LiteralPath $Path -ErrorAction Stop) {
    $line = $raw.Trim()
    if (!$line -or $line.StartsWith('#') -or !$line.Contains('=')) { continue }
    $parts = $line.Split('=', 2)
    $values[$parts[0].Trim()] = $parts[1].Trim().Trim('"')
  }
  return $values
}

function Write-EnvFile {
  param(
    [string]$Path,
    [hashtable]$Values
  )
  $orderedKeys = @(
    'UNIVERSAL_AI_STACK_HOME',
    'UNIVERSAL_AI_STACK_API_KEY',
    'API_SERVER_KEY',
    'HERMES_API_KEY',
    'HERMES_INFERENCE_PROVIDER',
    'HERMES_MODEL',
    'HERMES_REASONING_EFFORT',
    'HERMES_MAX_ITERATIONS',
    'REASONING_EFFORT',
    'KIMI_API_KEY',
    'KIMI_BASE_URL',
    'KIMI_MODEL_NAME',
    'KIMI_MODEL_CAPABILITIES',
    'KIMI_MODEL_MAX_CONTEXT_SIZE',
    'DISCORD_BOT_TOKEN',
    'DISCORD_ALLOWED_USERS',
    'DISCORD_ALLOWED_CHANNELS',
    'DISCORD_FREE_RESPONSE_CHANNELS',
    'DISCORD_HOME_CHANNEL',
    'DISCORD_HOME_CHANNEL_NAME',
    'DISCORD_OPUS_LIBRARY_PATH',
    'GATEWAY_ALLOWED_USERS',
    'HERMES_GIT_BASH_PATH',
    'TERMINAL_TIMEOUT',
    'TERMINAL_LIFETIME_SECONDS',
    'BROWSER_SESSION_TIMEOUT',
    'BROWSER_INACTIVITY_TIMEOUT',
    'TIRITH_ENABLED'
  )
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("# Generated by Universal AI Stack. Edit $SecretsEnv, then rerun Sync-UniversalAIStack.ps1.")
  $seen = @{}
  foreach ($key in $orderedKeys) {
    if ($Values.Contains($key)) {
      $lines.Add("$key=$($Values[$key])")
      $seen[$key] = $true
    }
  }
  foreach ($key in ($Values.Keys | Sort-Object)) {
    if ($seen.ContainsKey($key)) { continue }
    if ($key -match '^(OPENAI_API_KEY|OPENROUTER_API_KEY|ANTHROPIC_API_KEY|CLAUDE_API_KEY)$') { continue }
    $lines.Add("$key=$($Values[$key])")
  }
  $lines.Add('OPENAI_API_KEY=')
  $lines.Add('OPENROUTER_API_KEY=')
  $lines.Add('ANTHROPIC_API_KEY=')
  $lines.Add('CLAUDE_API_KEY=')
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllLines($Path, [string[]]$lines, $utf8NoBom)
}

function Protect-SecretsDir {
  param([string]$Path)
  $dir = Split-Path -Parent $Path
  New-Item -ItemType Directory -Force -Path $dir | Out-Null
  $userGrant = "$($env:USERNAME):(OI)(CI)F"
  & icacls $dir /inheritance:r /grant:r $userGrant 'SYSTEM:(OI)(CI)F' 'Administrators:(OI)(CI)F' | Out-Null
}

function Random-Token {
  $bytes = New-Object byte[] 32
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
  return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function Redact-PaperclipConfigBackup {
  param([string]$Path)
  if (!(Test-Path -LiteralPath $Path)) { return }
  $text = [System.IO.File]::ReadAllText($Path)
  $redacted = [regex]::Replace($text, '("apiKey"\s*:\s*")[^"]+(")', '$1[REDACTED_UNIVERSAL_ROUTER_KEY]$2')
  if ($redacted -ne $text) {
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $redacted, $utf8NoBom)
  }
}

New-Item -ItemType Directory -Force -Path $StateDir | Out-Null

$central = Read-EnvFile -Path $SecretsEnv
$hermes = Read-EnvFile -Path $HermesEnv
$merged = [ordered]@{}
foreach ($key in $hermes.Keys) { $merged[$key] = $hermes[$key] }
foreach ($key in $central.Keys) { $merged[$key] = $central[$key] }

$merged['UNIVERSAL_AI_STACK_HOME'] = $Root
if (!$merged.Contains('UNIVERSAL_AI_STACK_API_KEY') -or !$merged['UNIVERSAL_AI_STACK_API_KEY']) {
  if ($merged.Contains('API_SERVER_KEY') -and $merged['API_SERVER_KEY']) {
    $merged['UNIVERSAL_AI_STACK_API_KEY'] = $merged['API_SERVER_KEY']
  } else {
    $merged['UNIVERSAL_AI_STACK_API_KEY'] = Random-Token
  }
}
if (!$merged.Contains('API_SERVER_KEY') -or !$merged['API_SERVER_KEY']) {
  $merged['API_SERVER_KEY'] = $merged['UNIVERSAL_AI_STACK_API_KEY']
}
if (!$merged.Contains('HERMES_API_KEY') -or !$merged['HERMES_API_KEY']) {
  $merged['HERMES_API_KEY'] = $merged['API_SERVER_KEY']
}

$merged['HERMES_INFERENCE_PROVIDER'] = 'openai-codex'
$merged['HERMES_MODEL'] = 'gpt-5.5'
$merged['HERMES_REASONING_EFFORT'] = 'xhigh'
$merged['HERMES_MAX_ITERATIONS'] = '30'
$merged['REASONING_EFFORT'] = 'xhigh'
$merged['KIMI_BASE_URL'] = 'https://api.moonshot.ai/v1'
$merged['KIMI_MODEL_NAME'] = 'kimi-k2.6'
$merged['KIMI_MODEL_CAPABILITIES'] = 'thinking'
$merged['KIMI_MODEL_MAX_CONTEXT_SIZE'] = '262144'
$merged['TIRITH_ENABLED'] = '0'

Protect-SecretsDir -Path $SecretsEnv
Write-EnvFile -Path $SecretsEnv -Values $merged
Write-EnvFile -Path $HermesEnv -Values $merged

if (Test-Path -LiteralPath $PaperclipConfig) {
  $backup = "$PaperclipConfig.bak-universal-$(Get-Date -Format yyyyMMdd-HHmmss)"
  Copy-Item -LiteralPath $PaperclipConfig -Destination $backup -Force
  Redact-PaperclipConfigBackup -Path $backup
  $paperclip = Get-Content -LiteralPath $PaperclipConfig -Raw | ConvertFrom-Json
  if (!$paperclip.llm) {
    $paperclip | Add-Member -MemberType NoteProperty -Name llm -Value ([pscustomobject]@{})
  }
  $paperclip.llm.provider = 'openai'
  $paperclip.llm.baseUrl = 'http://127.0.0.1:18100/v1'
  $paperclip.llm.model = 'auto-coding'
  $paperclip.llm.apiKey = $merged['UNIVERSAL_AI_STACK_API_KEY']
  if (!$paperclip.telemetry) {
    $paperclip | Add-Member -MemberType NoteProperty -Name telemetry -Value ([pscustomobject]@{})
  }
  $paperclip.telemetry.enabled = $false
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($PaperclipConfig, ($paperclip | ConvertTo-Json -Depth 30), $utf8NoBom)
}

if (Test-Path -LiteralPath $KimiConfig) {
  $kimiText = [System.IO.File]::ReadAllText($KimiConfig)
  $scrubbed = [regex]::Replace(
    $kimiText,
    '(\[providers\.moonshot-ai\][\s\S]*?api_key\s*=\s*)".*?"',
    '$1""',
    1
  )
  if ($scrubbed -ne $kimiText) {
    $backup = "$KimiConfig.bak-universal-$(Get-Date -Format yyyyMMdd-HHmmss)"
    Copy-Item -LiteralPath $KimiConfig -Destination $backup -Force
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($KimiConfig, $scrubbed, $utf8NoBom)
  }
}

$hermesConfigReport = $null
$hermesConfigScript = Join-Path $Root 'scripts\Configure-HermesUniversalAI.ps1'
if (Test-Path -LiteralPath $hermesConfigScript) {
  try {
    $hermesConfigJson = & powershell -NoProfile -ExecutionPolicy Bypass -File $hermesConfigScript
    $hermesConfigReport = $hermesConfigJson | ConvertFrom-Json
  } catch {
    $hermesConfigReport = [pscustomobject]@{ error = $_.Exception.Message }
  }
}

$adapterScript = Join-Path $Root 'scripts\Install-UniversalAIAdapters.ps1'
$adapterReport = $null
if (Test-Path -LiteralPath $adapterScript) {
  try {
    $adapterJson = & powershell -NoProfile -ExecutionPolicy Bypass -File $adapterScript -JsonOnly
    $adapterReport = $adapterJson | ConvertFrom-Json
  } catch {
    $adapterReport = [pscustomobject]@{ error = $_.Exception.Message }
  }
}

$report = [ordered]@{
  time = (Get-Date).ToString('o')
  root = $Root
  centralEnv = (Test-Path -LiteralPath $SecretsEnv)
  hermesEnv = (Test-Path -LiteralPath $HermesEnv)
  hermesConfiguredForUniversalRouter = [bool]$hermesConfigReport -and -not [bool]$hermesConfigReport.error -and $hermesConfigReport.fallbackProvider -eq 'universal-router'
  paperclipConfiguredForUniversalRouter = $true
  paperclipKeyStoredAsRouterCompatibilityCopy = $true
  kimiApiKeyCentralized = (Test-Path -LiteralPath $KimiConfig) -and -not ([System.IO.File]::ReadAllText($KimiConfig) -match 'api_key\s*=\s*"sk-')
  agentAdaptersSynced = [bool]$adapterReport -and -not [bool]$adapterReport.error
  activeSecretKeys = @($merged.Keys | Where-Object { $_ -match 'KEY|TOKEN' -and $merged[$_] } | Sort-Object)
  canceledProviderKeysEmpty = @{
    OPENAI_API_KEY = -not [bool]$merged['OPENAI_API_KEY']
    OPENROUTER_API_KEY = -not [bool]$merged['OPENROUTER_API_KEY']
    ANTHROPIC_API_KEY = -not [bool]$merged['ANTHROPIC_API_KEY']
    CLAUDE_API_KEY = -not [bool]$merged['CLAUDE_API_KEY']
  }
}
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $StateDir 'last-sync-report.json'), ($report | ConvertTo-Json -Depth 6), $utf8NoBom)
$report | ConvertTo-Json -Depth 6
